"""eclass snapshot

Revision ID: 2b8d1c18c5f2
Revises: c58ec58b49d0
Create Date: 2026-02-14 03:17:23.694542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8d1c18c5f2'
down_revision: Union[str, Sequence[str], None] = 'c58ec58b49d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
