"""connect group major

Revision ID: 2fe484ff2111
Revises: 6bc875d7a4f8
Create Date: 2026-02-19 22:31:07.305158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe484ff2111'
down_revision: Union[str, Sequence[str], None] = '6bc875d7a4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_group_major_id_major'), 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'major', ['major_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key(op.f('fk_group_major_id_major'), 'group', 'major', ['major_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
