"""adding major db2

Revision ID: 3b829fca42fd
Revises: 1be2bd29f17f
Create Date: 2026-02-19 02:27:31.587259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b829fca42fd'
down_revision: Union[str, Sequence[str], None] = '1be2bd29f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendanceinfo', sa.Column('is_seen', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendanceinfo', 'is_seen')
    # ### end Alembic commands ###
