"""eclass snapshot

Revision ID: 4180b8755f0b
Revises: 2b8d1c18c5f2
Create Date: 2026-02-14 07:23:18.418843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4180b8755f0b'
down_revision: Union[str, Sequence[str], None] = '2b8d1c18c5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('eclass_registered', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'eclass_registered')
    # ### end Alembic commands ###
