"""last

Revision ID: 5ee1e9618646
Revises: 3b829fca42fd
Create Date: 2026-02-19 12:02:11.833756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ee1e9618646'
down_revision: Union[str, Sequence[str], None] = '3b829fca42fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('student_year_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'subject', 'studentyear', ['student_year_id'], ['id'])
    op.alter_column('superuser', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.alter_column('superuser', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'student_year_id')
    # ### end Alembic commands ###
