"""adding major db

Revision ID: 6c7ad0b4f4fc
Revises: 4180b8755f0b
Create Date: 2026-02-18 19:26:22.313283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c7ad0b4f4fc'
down_revision: Union[str, Sequence[str], None] = '4180b8755f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('major_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('major_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentyear',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starting_year', sa.Integer(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjectmajorlink',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subject', sa.Column('student_year_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'subject', 'studentyear', ['student_year_id'], ['id'])
    op.alter_column('superuser', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('superuser', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'student_year_id')
    op.drop_table('subjectmajorlink')
    op.drop_table('studentyear')
    op.drop_table('major')
    # ### end Alembic commands ###
