"""add room to TimeTable

Revision ID: a37b352e2aa3
Revises: 955331c96f5d
Create Date: 2026-02-08 00:36:09.357373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a37b352e2aa3'
down_revision: Union[str, Sequence[str], None] = '955331c96f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'group_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('timetable', 'room')
    # ### end Alembic commands ###
