"""adding major db2

Revision ID: bf47fa229429
Revises: 875e693412ac
Create Date: 2026-02-19 01:34:44.586466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf47fa229429'
down_revision: Union[str, Sequence[str], None] = '875e693412ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendanceinfo', sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('attendanceinfo', sa.Column('attendance', sa.Boolean(), nullable=False))
    op.add_column('attendanceinfo', sa.Column('absence', sa.Boolean(), nullable=False))
    op.add_column('attendanceinfo', sa.Column('late', sa.Boolean(), nullable=False))
    op.add_column('attendanceinfo', sa.Column('enrollment_id', sa.Uuid(), nullable=False))
    op.alter_column('attendanceinfo', 'date_of_week',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_foreign_key(None, 'attendanceinfo', 'enrollment', ['enrollment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendanceinfo', type_='foreignkey')
    op.alter_column('attendanceinfo', 'date_of_week',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('attendanceinfo', 'enrollment_id')
    op.drop_column('attendanceinfo', 'late')
    op.drop_column('attendanceinfo', 'absence')
    op.drop_column('attendanceinfo', 'attendance')
    op.drop_column('attendanceinfo', 'class_name')
    # ### end Alembic commands ###
