"""Classtime none value2

Revision ID: c58ec58b49d0
Revises: 
Create Date: 2026-02-13 00:10:52.650347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58ec58b49d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignment_enrollment_id_fkey'), 'assignment', type_='foreignkey')
    op.create_foreign_key(None, 'assignment', 'enrollment', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('class_group_id_fkey'), 'class', type_='foreignkey')
    op.drop_constraint(op.f('class_subject_id_fkey'), 'class', type_='foreignkey')
    op.drop_constraint(op.f('class_professor_id_fkey'), 'class', type_='foreignkey')
    op.create_foreign_key(None, 'class', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'class', 'professor', ['professor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('classtime_class_id_fkey'), 'classtime', type_='foreignkey')
    op.create_foreign_key(None, 'classtime', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quiz_enrollment_id_fkey'), 'quiz', type_='foreignkey')
    op.create_foreign_key(None, 'quiz', 'enrollment', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_group_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'group', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_group_id_fkey'), 'users', 'group', ['group_id'], ['id'])
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_enrollment_id_fkey'), 'quiz', 'enrollment', ['enrollment_id'], ['id'])
    op.drop_constraint(None, 'classtime', type_='foreignkey')
    op.create_foreign_key(op.f('classtime_class_id_fkey'), 'classtime', 'class', ['class_id'], ['id'])
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.create_foreign_key(op.f('class_professor_id_fkey'), 'class', 'professor', ['professor_id'], ['id'])
    op.create_foreign_key(op.f('class_subject_id_fkey'), 'class', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('class_group_id_fkey'), 'class', 'group', ['group_id'], ['id'])
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_enrollment_id_fkey'), 'assignment', 'enrollment', ['enrollment_id'], ['id'])
    # ### end Alembic commands ###
